server:
  http2:
    enabled: true
  port: '8090'
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        name: session_id
spring:
  liquibase:
    enabled: true
    change-log: 'classpath:liquibase/db-changelog.yaml'
  datasource:
    url: '${DB_URL}'
    username: '${DB_USER}'
    password: '${DB_PASS}'
    hikari:
      schema: public
  session:
    store-type: jdbc
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - 'file:static'
        - 'file:tiles'
      cache:
        cachecontrol:
          max-age: 1d
